Байкин Владимир ДЗ 2
idoleg/react-29.11 pull request #11
Opened 2019-12-09 12:04 UTC by chipcom

2019-12-11 11:27 UTC, idoleg requested changes
Отлично
Единственное замечание - исприавть разширение для сборки в файле вебпака. И PR можно принимать

2019-12-11 11:27 UTC, idoleg commented on chipcom/src/components/Form.jsx
> +  handleClick = this.handleClick.bind(this);
У вас часть обработчиков объявлены как обычные функции, часть - как стрелочные
Для учебы этот вариант хороший. Но в реальном коде такое не потерпят

2019-12-11 11:27 UTC, idoleg commented on chipcom/src/components/Message.jsx
> +          'flex-start, backgroundColor="red"' : 'flex-end' } }
Здорово, что вы потренировались со стилями, но в большинстве случаев это считается плохой практикой.

2019-12-11 11:27 UTC, idoleg commented on chipcom/src/components/MessageField.jsx
> +      <Message key={ message.id } name={message.name.length === 0 ? "Anonymous" : message.name} text={ message.content } />);
Проверку заполнения имени можно написать намного короче как `message.name || "Anonymous"`
И обратите внимание, что эту проверку логичнее перенести в компонент Message

2019-12-11 11:27 UTC, idoleg commented on chipcom/webpack.config.js
> +		filename: 'bundle.jsx',
Здесь "jsx" не нужен - это файл вашей сборки. Вот он как раз должен быть .js

2019-12-12 11:09 UTC, chipcom commented
что-то не получается создать новый pull request для ДЗ № 3

2019-12-13 15:00 UTC, idoleg approved these changes
1. Не самый лучший способ хранить все стили в одном файле. Лучше разбивать на разные компоненты. Если когда нибудь будете работать с реальным большим проектом, поймете эту боль)
2. Стили в JSX использовать можно, но это тоже плохой способ, по той же причине.
3. Попробуйте экран сервиса растянуть на всю высоту экрана
4. И просьба от меня. Настроить webpack-dev-server. Так и вам будет удобнее писать код, и мне проверять проще

С домашкой вы справились на отлично.

2019-12-13 15:00 UTC, merged